// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  image_text: dynamic(() => import("./ImageText")),
  testimonials: dynamic(() => import("./Testimonials")),
};
